spring:
  profiles:
    active: dev
server:
  port: 9999


dubbo:
  scan:
    base-packages: com.jason.dubbo.consumer.controller
  application:
    name: consumer
  registry:
        address: zookeeper://192.168.1.100:2181
        check: false
  protocol:
    name: dubbo
    port: 20880
    id: dubbo